# Настройки веб сервера
server:
  certificate:
    cert: ./cert/cert.pem
    key: ./cert/key.pem
    clientCert:
  port: 8050
  secure: false
  # set byte
  #    buffer_size:
  #      read:
  #      write:
  timeout:
    read: 30
    write: 30
    idle: 30
  # https://docs.gofiber.io/api/middleware/logger
  logger:
    format: "[${time}] ${ip} ${protocol} ${status} - ${latency} ${method} ${url}"
    filename: web
    time:
      # golang time format
      format: 15:04:05
      zone: Local
      # millisecond
      interval: 500

# Подключение к бд
database:
  server:
    hostname: cce-ucdev1-lt3
    port: 5432
  username: gonec
  password: N2I3eWZSRzZOSnpN
  name: gonecdb
  ssl: false
  connConfig:
    maxIdle: 10
    maxOpen: 100
    # set minutes
    maxLifetime: 60

# Настройки логера
logger:
  #	Ldate(1) = 1 << iota            the date in the local time zone: 2009/01/23
  # Ltime(2)                        the time in the local time zone: 01:23:23
  #	Lmicroseconds(4)                microsecond resolution: 01:23:23.123123.  assumes Ltime.
  #	Llongfile(8)                    full meta name and line number: /a/b/c/d.go:23
  #	Lshortfile(16)                  final meta name element and line number: d.go:23. overrides Llongfile
  #	LUTC(32)                        if Ldate or Ltime is set, use UTC rather than the local time zone
  #	Lmsgprefix(64)                  move the "prefix" from the beginning of the line to before the message
  #	LstdFlags(3) = Ldate | Ltime    initial values for the standard logger
  dirPath: logs
  info: 3
  error: 1 | 4 | 8
  debug: 1 | 4 | 8
  # size - в КБ
  # format - %name имя файл, %time - текущее время
  # path - путь куда перенести файл
  rotation:
    size: 10240
    format: "%name_old"
    path:
